(deftheme jocoo-material
  "Created 2025-04-02.")

(custom-theme-set-faces
 'jocoo-material
 '(default ((t (:family "Fira Code" :foundry "CTDB" :width normal :height 132 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#EEFFFF" :background "#212121" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#ffcb6b"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#89DDFF"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#ffcb6b"))))
 '(highlight ((t (:foreground "#171F24" :background "#c792ea"))))
 '(region ((t (:extend t :foreground "#80cbc4" :background "#406562"))))
 '(shadow ((t (:foreground "#585858"))))
 '(secondary-selection ((t (:extend t :background "#585858"))))
 '(trailing-whitespace ((t (:background "#f57373"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#82aaff"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#699854"))))
 '(font-lock-constant-face ((t (:foreground "#F78C6C"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#699854" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#82aaff"))))
 '(font-lock-keyword-face ((t (:foreground "#89DDFF"))))
 '(font-lock-negation-char-face ((t (:foreground "#89DDFF" :inherit (bold)))))
 '(font-lock-number-face ((t (:foreground "#F78C6C"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#89DDFF" :inherit (bold)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#89DDFF" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#89DDFF" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#c3e88d"))))
 '(font-lock-type-face ((t (:foreground "#c792ea"))))
 '(font-lock-variable-name-face ((t (:foreground "#ffcb6b"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line :position nil) :foreground "#c792ea"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#4a4a4a" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#EEFFFF" :background "#313131"))))
 '(mode-line ((t (:foreground "#A8A8A8" :background "#303030"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#c792ea"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#699854" :background "#202020"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#171F24" :background "#f57373"))))
 '(lazy-highlight ((t (:weight bold :foreground "#c3e88d" :background "#617446"))))
 '(match ((t (:weight bold :foreground "#c3e88d" :background "#171F24"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(ido-subdir ((t (:foreground "#bb80b3"))))
 '(ido-indicator ((t (:foreground "#f57373" :background "#212121")))))

(provide-theme 'jocoo-material)
